export const routes = {
	ROOT: '/',
	LOGIN: '/login',
	REGISTER: '/register',
	DASHBOARD: '/dashboard',
	DOCUMENT_TYPES: '/document-types',
	USERS: '/users',
	REQUESTS: {
		ROOT: '/requests',
		ARCHIVED: '/archived',
		INACTIVE: '/inactive',
	},
	PROFILE: '/profile',
	DOWNLOADABLES: '/downloadables',
	CMS: '/content-management',
	CONTACTS: '/contacts',
	TRACK_REQUEST: '/track-request',
	FORGOT_PASSWORD: '/forgot-password',
	RESET_PASSWORD: '/reset-password',
};
